//! Capability-based security model for unprivileged frontend and privileged backend.
//!
//! The presentation layer starts without application command authority and
//! receives scoped, time-limited tokens verified by the backend. These tokens
//! do not restrict operating-system privileges or authenticate a claimed PID.

use crate::error::{ErrorCode, MetisError, Result};
use moirai_crypto::{constant_time_eq_32, hmac_sha256};
use std::marker::PhantomData;

/// Bitflags representing distinct capability scopes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct CapabilityScope(pub u32);

impl CapabilityScope {
    /// No capabilities granted.
    pub const NONE: Self = Self(0);
    /// Permission to render UI presentation elements.
    pub const UI_RENDER: Self = Self(1 << 0);
    /// Permission to request clinical calculations.
    pub const SUBMIT_CALCULATION: Self = Self(1 << 1);
    /// Permission to inspect audit ledgers.
    pub const READ_AUDIT_LOG: Self = Self(1 << 2);
    /// Permission to stream continuous telemetry.
    pub const STREAM_TELEMETRY: Self = Self(1 << 3);
    /// Full administrator / supervisor capability.
    pub const SYSTEM_ADMIN: Self = Self(1 << 4);

    /// Checks if this scope contains all flags of `other`.
    #[must_use]
    pub const fn contains(&self, other: Self) -> bool {
        (self.0 & other.0) == other.0
    }

    /// Combines two capability scopes.
    #[must_use]
    pub const fn union(&self, other: Self) -> Self {
        Self(self.0 | other.0)
    }
}

/// Cryptographically signed capability token.
#[derive(Clone, PartialEq, Eq)]
pub struct CapabilityToken {
    /// Unique identifier for this token issuance.
    pub token_id: u64,
    /// Identifier of the principal/process to which this token was issued.
    pub principal_id: [u8; 16],
    /// Bitmask of granted capability scopes.
    pub scope: CapabilityScope,
    /// UTC timestamp of issuance (seconds since UNIX epoch).
    pub issued_at_secs: u64,
    /// UTC timestamp of expiration (seconds since UNIX epoch).
    pub expires_at_secs: u64,
    /// Issuance discriminator; transport sequence validation prevents replay.
    pub nonce: u64,
    /// HMAC-SHA256 signature generated by the privileged backend.
    pub signature: [u8; 32],
}

impl std::fmt::Debug for CapabilityToken {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Self {
            token_id,
            principal_id: _,
            scope,
            issued_at_secs,
            expires_at_secs,
            nonce: _,
            signature: _,
        } = self;
        formatter
            .debug_struct("CapabilityToken")
            .field("token_id", token_id)
            .field("scope", scope)
            .field("issued_at_secs", issued_at_secs)
            .field("expires_at_secs", expires_at_secs)
            .finish_non_exhaustive()
    }
}

impl CapabilityToken {
    /// Serializes the token claims (excluding the signature) for signing or verification.
    #[must_use]
    pub fn claims_bytes(&self) -> [u8; 56] {
        let mut bytes = [0u8; 56];
        bytes[0..8].copy_from_slice(&self.token_id.to_be_bytes());
        bytes[8..24].copy_from_slice(&self.principal_id);
        bytes[24..28].copy_from_slice(&self.scope.0.to_be_bytes());
        bytes[28..36].copy_from_slice(&self.issued_at_secs.to_be_bytes());
        bytes[36..44].copy_from_slice(&self.expires_at_secs.to_be_bytes());
        bytes[44..52].copy_from_slice(&self.nonce.to_be_bytes());
        bytes
    }

    /// Creates a newly issued capability token signed with the provided master secret key.
    #[must_use]
    pub fn issue(
        token_id: u64,
        principal_id: [u8; 16],
        scope: CapabilityScope,
        issued_at_secs: u64,
        duration_secs: u64,
        nonce: u64,
        backend_master_key: &[u8],
    ) -> Self {
        let mut token = Self {
            token_id,
            principal_id,
            scope,
            issued_at_secs,
            expires_at_secs: issued_at_secs.saturating_add(duration_secs),
            nonce,
            signature: [0u8; 32],
        };
        let claims = token.claims_bytes();
        token.signature = hmac_sha256(backend_master_key, &claims);
        token
    }

    /// Verifies the token's cryptographic signature against the master secret key.
    ///
    /// # Errors
    /// Rejects a token whose MAC does not match its claims.
    pub fn verify_signature(&self, backend_master_key: &[u8]) -> Result<()> {
        let claims = self.claims_bytes();
        let expected_signature = hmac_sha256(backend_master_key, &claims);
        if !constant_time_eq_32(&self.signature, &expected_signature) {
            return Err(MetisError::capability(
                ErrorCode::InvalidCapabilitySignature,
                "Capability token signature verification failed",
            ));
        }
        Ok(())
    }

    /// Verifies that the token is valid for the given timestamp and required scope.
    ///
    /// # Errors
    /// Rejects invalid MACs, timestamps outside [issued, expires), or missing scope.
    pub fn verify(
        &self,
        required_scope: CapabilityScope,
        current_time_secs: u64,
        backend_master_key: &[u8],
    ) -> Result<()> {
        self.verify_signature(backend_master_key)?;

        if current_time_secs < self.issued_at_secs || current_time_secs >= self.expires_at_secs {
            return Err(MetisError::capability(
                ErrorCode::CapabilityExpired,
                format!(
                    "Capability token expired at {} (current: {})",
                    self.expires_at_secs, current_time_secs
                ),
            ));
        }

        if !self.scope.contains(required_scope) {
            return Err(MetisError::capability(
                ErrorCode::InsufficientScope,
                format!(
                    "Token scope 0x{:08X} lacks required scope 0x{:08X}",
                    self.scope.0, required_scope.0
                ),
            ));
        }

        Ok(())
    }
}

/// Snapshot witness of a capability check at the supplied timestamp.
///
/// Functions requiring high assurance can take `VerifiedCapability<SCOPE>` as an
/// witness argument. This does not extend token validity or bind an OS identity.
#[derive(Debug, Clone, Copy)]
pub struct VerifiedCapability<const SCOPE: u32> {
    token_id: u64,
    _phantom: PhantomData<()>,
}

impl<const SCOPE: u32> VerifiedCapability<SCOPE> {
    /// Unforgeable constructor: only succeeds if the token has verified signature,
    /// expiration, and required scope.
    ///
    /// # Errors
    /// Propagates authentication, lifetime and scope failures.
    pub fn prove(
        token: &CapabilityToken,
        current_time_secs: u64,
        backend_master_key: &[u8],
    ) -> Result<Self> {
        token.verify(
            CapabilityScope(SCOPE),
            current_time_secs,
            backend_master_key,
        )?;
        Ok(Self {
            token_id: token.token_id,
            _phantom: PhantomData,
        })
    }

    /// Returns the verified token ID.
    #[must_use]
    pub const fn token_id(&self) -> u64 {
        self.token_id
    }
}
