//! Authenticated browser WebSocket service composition.

use crate::service::{BackendService, Clock};
use metis_core::error::{ErrorCode, MetisError, Result};
use metis_core::protocol::TargetCapability;
use metis_ipc::AsyncIpcServer;
use moirai_async::io::{AsyncRead, AsyncWrite};
use moirai_http::{WebSocketConfig, accept_websocket_with_validator};
use std::io;
use std::time::Duration;

/// Serves one browser WebSocket session after a pre-response origin check.
///
/// The caller must construct `service` with [`BackendService::with_trusted_context`]
/// using a principal generated by the trusted host. The HTTP upgrade validator
/// observes the request's `Origin` header before writing `101 Switching
/// Protocols`; the asynchronous IPC server then applies the backend's normal
/// handshake, replay, capability, and audit contracts.
///
/// # Errors
/// Returns invalid-origin, protocol, handler, transport, or deadline failures.
/// A service without a trusted host context is rejected before accepting the
/// WebSocket.
pub async fn serve_browser_websocket<S, C>(
    stream: S,
    config: WebSocketConfig,
    service: BackendService<C>,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    serve_browser_websocket_with_policy(stream, config, service, None).await
}

/// Serves one browser session with a bounded delayed clinical response probe.
///
/// The delay is applied only to a successful `ClinicalCalcResp`. It exercises
/// the same authenticated service and WebSocket path as the normal browser
/// host, allowing a stopped or remounted WASM application to be checked for
/// stale DOM mutation. The delay is implemented by Moirai's cancellable timer.
///
/// # Errors
/// Returns the normal browser-service failures or [`ErrorCode::Timeout`] when
/// `response_delay` exceeds [`metis_ipc::MAX_CLINICAL_RESPONSE_DELAY`].
pub async fn serve_browser_websocket_with_response_delay<S, C>(
    stream: S,
    config: WebSocketConfig,
    service: BackendService<C>,
    response_delay: Duration,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    serve_browser_websocket_with_policy(stream, config, service, Some(response_delay)).await
}

async fn serve_browser_websocket_with_policy<S, C>(
    stream: S,
    config: WebSocketConfig,
    mut service: BackendService<C>,
    response_delay: Option<Duration>,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    if !service.has_trusted_context() {
        return Err(MetisError::capability(
            ErrorCode::InvalidPrincipal,
            "Browser service requires a trusted host session context",
        ));
    }
    service.add_target_capability(TargetCapability::BrowserWebSocket)?;
    let policy = service.browser_policy().clone();
    let (socket, _upgrade) = accept_websocket_with_validator(stream, config, move |request| {
        policy
            .observe_origin(request.origin())
            .map(|_| ())
            .map_err(origin_error)
    })
    .await
    .map_err(|error| websocket_error(&error))?;
    let server = AsyncIpcServer::new(socket);
    let mut server = match response_delay {
        Some(delay) => server.with_clinical_response_delay(delay)?,
        None => server,
    };
    server.run(&mut service).await
}

fn origin_error(error: MetisError) -> io::Error {
    io::Error::new(io::ErrorKind::PermissionDenied, error)
}

fn websocket_error(error: &io::Error) -> MetisError {
    if let Some(error) = error
        .get_ref()
        .and_then(|source| source.downcast_ref::<MetisError>())
    {
        return error.clone();
    }
    let code = match error.kind() {
        io::ErrorKind::InvalidData | io::ErrorKind::InvalidInput => ErrorCode::MalformedPayload,
        io::ErrorKind::TimedOut | io::ErrorKind::WouldBlock => ErrorCode::Timeout,
        io::ErrorKind::UnexpectedEof => ErrorCode::FrameTruncated,
        io::ErrorKind::BrokenPipe | io::ErrorKind::ConnectionReset => ErrorCode::ConnectionClosed,
        _ => ErrorCode::TransportBroken,
    };
    if matches!(code, ErrorCode::MalformedPayload) {
        MetisError::protocol(code, error.to_string())
    } else {
        MetisError::transport(code, error.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::clinical::SafetyEnvelope;
    use crate::plugins::PluginExecutor;
    use crate::service::SystemClock;
    use metis_core::capability::CapabilityScope;
    use metis_core::host::{HostContext, HostOrigin, HostPolicy, HostSessionId, WindowId};
    use metis_core::protocol::{
        ClinicalCalcRequestPayload, ClinicalCalcResponsePayload, HandshakeRequestPayload,
        HandshakeResponsePayload, MessageType, PROTOCOL_VERSION, Plugin, PluginDescriptor,
        PluginInvocationPayload, PluginInvocationResponsePayload, PluginOperation,
        RemoteEventPayload, TargetCapability, TargetCapabilityPayload, build_frame,
    };
    use moirai_async::io::{AsyncReadExt, AsyncWriteExt};
    use moirai_async::net::{TcpListener, TcpStream};
    use moirai_http::WebSocketConfig;
    use std::io::{self, ErrorKind};
    use std::time::Duration;

    const ORIGIN: &str = "http://127.0.0.1:8080";
    const PRINCIPAL: [u8; 16] = [0x66; 16];
    const MASK: [u8; 4] = [0x13, 0x37, 0xa5, 0x5a];

    static PLUGIN_COMMANDS: [PluginOperation; 1] = [PluginOperation::new(
        "increment",
        CapabilityScope::SUBMIT_CALCULATION,
    )];

    struct WebSocketPlugin;

    impl Plugin for WebSocketPlugin {
        const DESCRIPTOR: PluginDescriptor =
            PluginDescriptor::new("websocket", 1, &PLUGIN_COMMANDS, &[]);
    }

    impl PluginExecutor for WebSocketPlugin {
        fn invoke(&mut self, operation_name: &str, body: &[u8]) -> metis_core::Result<Vec<u8>> {
            if operation_name != "increment" {
                return Err(metis_core::MetisError::capability(
                    metis_core::ErrorCode::PluginOperationNotFound,
                    "WebSocket test executor received an undeclared operation",
                ));
            }
            Ok(body.iter().map(|byte| byte.wrapping_add(1)).collect())
        }
    }

    fn service() -> BackendService {
        let origin = HostOrigin::parse(ORIGIN).expect("test origin");
        let policy = HostPolicy::new(origin.clone(), WindowId::new(1).expect("test window"));
        let context = HostContext::new(
            origin,
            WindowId::new(1).expect("test window"),
            HostSessionId::new(PRINCIPAL).expect("test principal"),
        );
        let mut service = BackendService::with_trusted_context(
            [7; 32],
            SafetyEnvelope::default(),
            SystemClock::default(),
            policy,
            context,
        )
        .expect("trusted context");
        service
            .register_plugin(WebSocketPlugin)
            .expect("test plugin");
        service
    }

    fn config() -> WebSocketConfig {
        WebSocketConfig::new(
            4096,
            16,
            65_560,
            Duration::from_secs(2),
            Duration::from_secs(2),
        )
    }

    fn upgrade_request(origin: &str) -> Vec<u8> {
        format!(
            "GET /socket HTTP/1.1\r\nHost: 127.0.0.1:8765\r\nUpgrade: websocket\r\nConnection: Upgrade\r\nSec-WebSocket-Version: 13\r\nSec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==\r\nOrigin: {origin}\r\n\r\n"
        )
        .into_bytes()
    }

    fn masked_binary(payload: &[u8]) -> Vec<u8> {
        masked_frame(0x2, payload)
    }

    fn masked_close() -> Vec<u8> {
        masked_control(0x8, &1000_u16.to_be_bytes())
    }

    fn handshake_frame(sequence: u64) -> Vec<u8> {
        build_frame(
            MessageType::HandshakeReq,
            sequence,
            &HandshakeRequestPayload {
                client_version: PROTOCOL_VERSION,
                client_process_id: 42,
                principal_id: PRINCIPAL,
            }
            .encode(),
        )
        .expect("handshake frame")
    }

    fn masked_control(opcode: u8, payload: &[u8]) -> Vec<u8> {
        assert!(payload.len() <= 125, "test control frame exceeds RFC bound");
        masked_frame(opcode, payload)
    }

    fn masked_frame(opcode: u8, payload: &[u8]) -> Vec<u8> {
        let mut frame = Vec::with_capacity(payload.len() + 14);
        frame.push(0x80 | opcode);
        match payload.len() {
            length @ 0..=125 => frame.push(0x80 | u8::try_from(length).expect("short length")),
            length @ 126..=65_535 => {
                frame.push(0x80 | 0x7e);
                frame.extend_from_slice(
                    &u16::try_from(length)
                        .expect("extended length")
                        .to_be_bytes(),
                );
            }
            length => {
                frame.push(0x80 | 127);
                frame.extend_from_slice(&u64::try_from(length).expect("long length").to_be_bytes());
            }
        }
        frame.extend_from_slice(&MASK);
        frame.extend(
            payload
                .iter()
                .zip(MASK.iter().cycle())
                .map(|(byte, mask)| byte ^ mask),
        );
        frame
    }

    async fn read_upgrade_response(stream: &mut TcpStream) -> io::Result<Vec<u8>> {
        let mut response = Vec::with_capacity(256);
        loop {
            let mut byte = [0; 1];
            let count = stream.read(&mut byte).await?;
            if count == 0 {
                break;
            }
            response.push(byte[0]);
            if response.ends_with(b"\r\n\r\n") {
                break;
            }
            if response.len() > 4096 {
                return Err(io::Error::new(ErrorKind::InvalidData, "response too large"));
            }
        }
        Ok(response)
    }

    async fn read_server_binary(stream: &mut TcpStream) -> io::Result<Vec<u8>> {
        let mut header = [0; 2];
        stream.read_exact(&mut header).await?;
        if header[0] != 0x82 || header[1] & 0x80 != 0 {
            return Err(io::Error::new(
                ErrorKind::InvalidData,
                "server response is not an unmasked binary frame",
            ));
        }
        let length = match header[1] & 0x7f {
            length @ 0..=125 => usize::from(length),
            126 => {
                let mut bytes = [0; 2];
                stream.read_exact(&mut bytes).await?;
                usize::from(u16::from_be_bytes(bytes))
            }
            127 => {
                let mut bytes = [0; 8];
                stream.read_exact(&mut bytes).await?;
                usize::try_from(u64::from_be_bytes(bytes)).map_err(|_| {
                    io::Error::new(ErrorKind::InvalidData, "server frame length is too large")
                })?
            }
            _ => {
                return Err(io::Error::new(
                    ErrorKind::InvalidData,
                    "invalid frame length",
                ));
            }
        };
        let mut payload = vec![0; length];
        stream.read_exact(&mut payload).await?;
        Ok(payload)
    }

    async fn run_valid_exchange() -> io::Result<(Vec<u8>, Vec<u8>, Vec<u8>, Vec<u8>, Vec<u8>)> {
        let listener = TcpListener::bind("127.0.0.1:0").await?;
        let address = listener.local_addr()?;
        let server = std::thread::spawn(move || {
            moirai_executor::block_on(async move {
                let (stream, _) = listener.accept().await?;
                serve_browser_websocket(stream, config(), service()).await
            })
        });

        let result = async {
            let mut client = TcpStream::connect(&address.to_string()).await?;
            client.write_all(&upgrade_request(ORIGIN)).await?;
            client.flush().await?;
            let response = read_upgrade_response(&mut client).await?;
            if !response.starts_with(b"HTTP/1.1 101 Switching Protocols\r\n") {
                return Err(io::Error::new(
                    ErrorKind::InvalidData,
                    "authorized origin did not receive a switching response",
                ));
            }

            let handshake = handshake_frame(1);
            client.write_all(&masked_binary(&handshake)).await?;
            client.flush().await?;
            let handshake_response = read_server_binary(&mut client).await?;
            let mut handshake_wire = handshake_response.as_slice();
            let (header, payload) = metis_ipc::read_frame(&mut handshake_wire)
                .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?;
            if header.msg_type != MessageType::HandshakeResp {
                return Err(io::Error::new(
                    ErrorKind::InvalidData,
                    "handshake response type mismatch",
                ));
            }
            let token = HandshakeResponsePayload::decode(&payload)
                .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?
                .initial_token;

            let target_request = build_frame(MessageType::TargetCapabilityReq, 2, &[])
                .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?;
            client.write_all(&masked_binary(&target_request)).await?;
            client.flush().await?;
            let target_response = read_server_binary(&mut client).await?;

            let calculation = build_frame(
                MessageType::ClinicalCalcReq,
                3,
                &ClinicalCalcRequestPayload {
                    token: token.clone(),
                    patient_id: "PT-9042-ALPHA".to_owned(),
                    weight_kg: 72.5,
                    concentration_mg_ml: 4.0,
                    target_dose_mcg_kg_min: 0.5,
                }
                .encode()
                .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?,
            )
            .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?;
            client.write_all(&masked_binary(&calculation)).await?;
            client.flush().await?;
            let calculation_response = read_server_binary(&mut client).await?;
            let event = read_server_binary(&mut client).await?;
            let plugin = PluginInvocationPayload::new(token, "websocket", "increment", [2, 5, 10])
                .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?;
            let plugin = build_frame(
                MessageType::PluginInvokeReq,
                4,
                &plugin
                    .encode()
                    .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?,
            )
            .map_err(|error| io::Error::new(ErrorKind::InvalidData, error.to_string()))?;
            client.write_all(&masked_binary(&plugin)).await?;
            client.flush().await?;
            let plugin_response = read_server_binary(&mut client).await?;
            client.write_all(&masked_close()).await?;
            client.flush().await?;
            Ok((
                handshake_response,
                target_response,
                calculation_response,
                event,
                plugin_response,
            ))
        }
        .await;

        let server_result = server
            .join()
            .map_err(|_| io::Error::other("WebSocket server thread panicked"))?
            .map_err(|error: MetisError| io::Error::other(error.to_string()));
        if let Err(error) = server_result {
            return Err(io::Error::other(format!("server: {error}")));
        }
        result
    }

    #[test]
    fn authenticated_loopback_preserves_handshake_and_clinical_values() {
        let (handshake, target, calculation, event_wire, plugin_wire) =
            moirai_executor::block_on(run_valid_exchange()).expect("loopback exchange");
        let mut handshake_wire = handshake.as_slice();
        let (handshake_header, handshake_payload) =
            metis_ipc::read_frame(&mut handshake_wire).expect("handshake frame");
        assert_eq!(handshake_header.sequence_id, 1);
        assert_eq!(handshake_header.msg_type, MessageType::HandshakeResp);
        let token = HandshakeResponsePayload::decode(&handshake_payload)
            .expect("handshake payload")
            .initial_token;
        let mut target_wire = target.as_slice();
        let (target_header, target_payload) =
            metis_ipc::read_frame(&mut target_wire).expect("target frame");
        assert_eq!(target_header.sequence_id, 2);
        assert_eq!(target_header.msg_type, MessageType::TargetCapabilityResp);
        let target = TargetCapabilityPayload::decode(&target_payload).expect("target payload");
        assert!(target.supports(TargetCapability::BrowserWebSocket));
        let mut calculation_wire = calculation.as_slice();
        let (calculation_header, calculation_payload) =
            metis_ipc::read_frame(&mut calculation_wire).expect("calculation frame");
        assert_eq!(calculation_header.sequence_id, 3);
        assert_eq!(calculation_header.msg_type, MessageType::ClinicalCalcResp);
        let result =
            ClinicalCalcResponsePayload::decode(&calculation_payload).expect("calculation payload");
        assert_eq!(result.rate_ml_hr.to_bits(), 0.54375_f64.to_bits());
        assert_eq!(result.drug_rate_mg_hr.to_bits(), 2.175_f64.to_bits());
        assert!(!result.is_pediatric);
        assert_ne!(token.signature, [0; 32]);
        let mut event_wire = event_wire.as_slice();
        let (event_header, event_payload) =
            metis_ipc::read_frame(&mut event_wire).expect("event frame");
        assert_eq!(event_header.sequence_id, result.audit_sequence_id);
        assert_eq!(event_header.msg_type, MessageType::TelemetryStreamEvent);
        let event = RemoteEventPayload::decode(&event_payload).expect("event envelope");
        assert_eq!(event.name(), "clinical.result");
        assert_eq!(event.event_id().get(), result.audit_sequence_id);
        assert_eq!(
            event
                .decode_as::<ClinicalCalcResponsePayload>()
                .expect("typed event"),
            result
        );
        let mut plugin_wire = plugin_wire.as_slice();
        let (plugin_header, plugin_payload) =
            metis_ipc::read_frame(&mut plugin_wire).expect("plugin frame");
        assert_eq!(plugin_header.sequence_id, 4);
        assert_eq!(plugin_header.msg_type, MessageType::PluginInvokeResp);
        assert_eq!(
            PluginInvocationResponsePayload::decode(&plugin_payload)
                .expect("plugin payload")
                .body(),
            [3, 6, 11]
        );
    }

    #[test]
    fn origin_rejection_happens_before_switching_protocols_response() {
        let result = std::thread::spawn(|| {
            moirai_executor::block_on(async {
                let listener = TcpListener::bind("127.0.0.1:0").await?;
                let address = listener.local_addr()?;
                let server = std::thread::spawn(move || {
                    moirai_executor::block_on(async move {
                        let (stream, _) = listener.accept().await?;
                        serve_browser_websocket(stream, config(), service()).await
                    })
                });
                let mut client = TcpStream::connect(&address.to_string()).await?;
                client
                    .write_all(&upgrade_request("http://evil.example"))
                    .await?;
                client.flush().await?;
                let response = read_upgrade_response(&mut client).await?;
                if response.windows(3).any(|window| window == b"101") {
                    return Err(io::Error::new(
                        ErrorKind::PermissionDenied,
                        "rejected origin received a switching response",
                    ));
                }
                let server_error = server
                    .join()
                    .map_err(|_| io::Error::other("WebSocket server thread panicked"))?
                    .expect_err("origin must be rejected");
                if server_error.code != ErrorCode::NavigationDenied {
                    return Err(io::Error::new(
                        ErrorKind::PermissionDenied,
                        format!("unexpected origin error: {}", server_error.code.as_str()),
                    ));
                }
                Ok(())
            })
        })
        .join()
        .map_err(|_| io::Error::other("origin test thread panicked"))
        .and_then(|result| result);
        result.expect("origin rejection");
    }

    #[test]
    fn service_rejects_replayed_sequence_after_handshake() {
        let result = std::thread::spawn(|| {
            moirai_executor::block_on(async {
                let listener = TcpListener::bind("127.0.0.1:0").await?;
                let address = listener.local_addr()?;
                let server = std::thread::spawn(move || {
                    moirai_executor::block_on(async move {
                        let (stream, _) = listener.accept().await?;
                        serve_browser_websocket(stream, config(), service()).await
                    })
                });
                let mut client = TcpStream::connect(&address.to_string()).await?;
                client.write_all(&upgrade_request(ORIGIN)).await?;
                client.flush().await?;
                let response = read_upgrade_response(&mut client).await?;
                if !response.starts_with(b"HTTP/1.1 101 Switching Protocols\r\n") {
                    return Err(io::Error::new(
                        ErrorKind::InvalidData,
                        "authorized origin did not receive a switching response",
                    ));
                }
                let handshake = handshake_frame(1);
                client.write_all(&masked_binary(&handshake)).await?;
                client.flush().await?;
                let _ = read_server_binary(&mut client).await?;
                client.write_all(&masked_binary(&handshake)).await?;
                client.flush().await?;
                let server_error = server
                    .join()
                    .map_err(|_| io::Error::other("WebSocket server thread panicked"))?
                    .expect_err("replayed sequence must be rejected");
                if server_error.code != ErrorCode::ReplayDetected {
                    return Err(io::Error::new(
                        ErrorKind::InvalidData,
                        format!("unexpected replay error: {}", server_error.code.as_str()),
                    ));
                }
                Ok(())
            })
        })
        .join()
        .map_err(|_| io::Error::other("replay test thread panicked"))
        .and_then(|result| result);
        result.expect("replay rejection");
    }

    #[test]
    fn service_rejects_oversized_websocket_messages() {
        let result = std::thread::spawn(|| {
            moirai_executor::block_on(async {
                let listener = TcpListener::bind("127.0.0.1:0").await?;
                let address = listener.local_addr()?;
                let server = std::thread::spawn(move || {
                    moirai_executor::block_on(async move {
                        let (stream, _) = listener.accept().await?;
                        serve_browser_websocket(stream, config(), service()).await
                    })
                });
                let mut client = TcpStream::connect(&address.to_string()).await?;
                client.write_all(&upgrade_request(ORIGIN)).await?;
                client.flush().await?;
                let response = read_upgrade_response(&mut client).await?;
                if !response.starts_with(b"HTTP/1.1 101 Switching Protocols\r\n") {
                    return Err(io::Error::new(
                        ErrorKind::InvalidData,
                        "authorized origin did not receive a switching response",
                    ));
                }
                let oversized = vec![0; 65_561];
                client.write_all(&masked_binary(&oversized)).await?;
                client.flush().await?;
                let server_error = server
                    .join()
                    .map_err(|_| io::Error::other("WebSocket server thread panicked"))?
                    .expect_err("oversized message must be rejected");
                if server_error.code != ErrorCode::PayloadTooLarge {
                    return Err(io::Error::new(
                        ErrorKind::InvalidData,
                        format!("unexpected size error: {}", server_error.code.as_str()),
                    ));
                }
                Ok(())
            })
        })
        .join()
        .map_err(|_| io::Error::other("oversize test thread panicked"))
        .and_then(|result| result);
        result.expect("oversize rejection");
    }
}
