//! Authenticated browser WebSocket service composition.

use crate::service::{BackendService, Clock};
use metis_core::error::{ErrorCode, MetisError, Result};
use metis_core::protocol::TargetCapability;
use metis_ipc::AsyncIpcServer;
use moirai_async::io::{AsyncRead, AsyncWrite};
use moirai_http::{WebSocketConfig, accept_websocket_with_validator};
use std::io;
use std::time::Duration;

/// Serves one browser WebSocket session after a pre-response origin check.
///
/// The caller must construct `service` with [`BackendService::with_trusted_context`]
/// using a principal generated by the trusted host. The HTTP upgrade validator
/// observes the request's `Origin` header before writing `101 Switching
/// Protocols`; the asynchronous IPC server then applies the backend's normal
/// handshake, replay, capability, and audit contracts.
///
/// # Errors
/// Returns invalid-origin, protocol, handler, transport, or deadline failures.
/// A service without a trusted host context is rejected before accepting the
/// WebSocket.
pub async fn serve_browser_websocket<S, C>(
    stream: S,
    config: WebSocketConfig,
    service: BackendService<C>,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    serve_browser_websocket_with_policy(stream, config, service, None).await
}

/// Serves one browser session with a bounded delayed clinical response probe.
///
/// The delay is applied only to a successful `ClinicalCalcResp`. It exercises
/// the same authenticated service and WebSocket path as the normal browser
/// host, allowing a stopped or remounted WASM application to be checked for
/// stale DOM mutation. The delay is implemented by Moirai's cancellable timer.
///
/// # Errors
/// Returns the normal browser-service failures or [`ErrorCode::Timeout`] when
/// `response_delay` exceeds [`metis_ipc::MAX_CLINICAL_RESPONSE_DELAY`].
pub async fn serve_browser_websocket_with_response_delay<S, C>(
    stream: S,
    config: WebSocketConfig,
    service: BackendService<C>,
    response_delay: Duration,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    serve_browser_websocket_with_policy(stream, config, service, Some(response_delay)).await
}

async fn serve_browser_websocket_with_policy<S, C>(
    stream: S,
    config: WebSocketConfig,
    mut service: BackendService<C>,
    response_delay: Option<Duration>,
) -> Result<()>
where
    S: AsyncRead + AsyncWrite + Unpin,
    C: Clock,
{
    if !service.has_trusted_context() {
        return Err(MetisError::capability(
            ErrorCode::InvalidPrincipal,
            "Browser service requires a trusted host session context",
        ));
    }
    service.add_target_capability(TargetCapability::BrowserWebSocket)?;
    let policy = service.browser_policy().clone();
    let (socket, _upgrade) = accept_websocket_with_validator(stream, config, move |request| {
        policy
            .observe_origin(request.origin())
            .map(|_| ())
            .map_err(origin_error)
    })
    .await
    .map_err(|error| websocket_error(&error))?;
    let server = AsyncIpcServer::new(socket);
    let mut server = match response_delay {
        Some(delay) => server.with_clinical_response_delay(delay)?,
        None => server,
    };
    server.run(&mut service).await
}

fn origin_error(error: MetisError) -> io::Error {
    io::Error::new(io::ErrorKind::PermissionDenied, error)
}

fn websocket_error(error: &io::Error) -> MetisError {
    if let Some(error) = error
        .get_ref()
        .and_then(|source| source.downcast_ref::<MetisError>())
    {
        return error.clone();
    }
    let code = match error.kind() {
        io::ErrorKind::InvalidData | io::ErrorKind::InvalidInput => ErrorCode::MalformedPayload,
        io::ErrorKind::TimedOut | io::ErrorKind::WouldBlock => ErrorCode::Timeout,
        io::ErrorKind::UnexpectedEof => ErrorCode::FrameTruncated,
        io::ErrorKind::BrokenPipe | io::ErrorKind::ConnectionReset => ErrorCode::ConnectionClosed,
        _ => ErrorCode::TransportBroken,
    };
    if matches!(code, ErrorCode::MalformedPayload) {
        MetisError::protocol(code, error.to_string())
    } else {
        MetisError::transport(code, error.to_string())
    }
}

#[cfg(test)]
#[path = "websocket_tests.rs"]
mod tests;
