//! Native display fixtures for provider-owned JPEG arithmetic streams.

use metis_platform::{Color, Framebuffer, Rect};
use metis_ui_lang::RasterImage;
use std::error::Error;

use super::jpeg_gallery::render_sample;

// Exact copies of Consus `tests/fixtures/jpeg/dc-*-arithmetic.jpg`, produced
// by libjpeg-turbo 3.1.2 `jpegtran` without requantization.
const SEQUENTIAL: &[u8] = &[
    0xff, 0xd8, 0xff, 0xe0, 0, 0x10, 0x4a, 0x46, 0x49, 0x46, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0xff,
    0xdb, 0, 0x43, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 0xff, 0xc9, 0, 0x0b, 8, 0, 8, 0, 0x18, 1, 1, 0x11, 0, 0xff, 0xcc, 0, 6, 0,
    0x10, 0x10, 5, 0xff, 0xda, 0, 8, 1, 1, 0, 0, 0x3f, 0, 0xff, 0, 0xf8, 0x5d, 0xa1, 0x50, 0xff,
    0xd9,
];
const PROGRESSIVE: &[u8] = &[
    0xff, 0xd8, 0xff, 0xe0, 0, 0x10, 0x4a, 0x46, 0x49, 0x46, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0xff,
    0xdb, 0, 0x43, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    1, 1, 1, 1, 1, 1, 0xff, 0xca, 0, 0x0b, 8, 0, 8, 0, 0x18, 1, 1, 0x11, 0, 0xff, 0xcc, 0, 4, 0,
    0x10, 0xff, 0xda, 0, 8, 1, 1, 0, 0, 0, 2, 0xff, 0, 0xde, 0xcb, 0x2a, 0xff, 0xcc, 0, 4, 0x10, 5,
    0xff, 0xda, 0, 8, 1, 1, 0, 1, 0x3f, 2, 0xc0, 0xff, 0xda, 0, 8, 1, 1, 0, 0, 0, 0x21, 0x60, 0xff,
    0xcc, 0, 4, 0x10, 5, 0xff, 0xda, 0, 8, 1, 1, 0, 1, 0x3f, 0x21, 0xc0, 0xff, 0xda, 0, 8, 1, 1, 0,
    0, 0, 0x10, 0x60, 0xff, 0xcc, 0, 4, 0x10, 5, 0xff, 0xda, 0, 8, 1, 1, 0, 1, 0x3f, 0x10, 0xc0,
    0xff, 0xd9,
];
// Exact copy of Consus `tests/fixtures/jpeg/lossless-12-restart-0-arithmetic.jpg`,
// generated by the unmodified ISO reference implementation at
// c719010a26ce0c666e98b2acf924ad5fc24b4f5d.
const LOSSLESS_TWELVE: &[u8] = &[
    0xff, 0xd8, 0xff, 0xee, 0, 0x0e, 0x41, 0x64, 0x6f, 0x62, 0x65, 0, 0x64, 0, 0, 0, 0, 0, 0xff,
    0xcb, 0, 0x0b, 12, 0, 4, 0, 5, 1, 0, 0x11, 0, 0xff, 0xcc, 0, 4, 0, 0x10, 0xff, 0xda, 0, 8, 1,
    0, 0, 4, 0, 0, 0xff, 0, 0xfc, 0x1a, 0xb7, 0xa3, 0x57, 0xa9, 0xd6, 0x34, 0x6d, 0xb7, 0xcd, 0xe3,
    0x9d, 0x2d, 0x68, 0x9b, 0x84, 0x35, 0x97, 0xc6, 0x7e, 0xd7, 0xfd, 0x62, 0x1d, 0xbb, 0x22, 0x26,
    0xf8, 0x66, 0x5c, 0xff, 0xd9,
];

pub(super) fn render(frame: &mut Framebuffer) -> Result<(), Box<dyn Error>> {
    let sequential = RasterImage::decode(SEQUENTIAL)?;
    let progressive = RasterImage::decode(PROGRESSIVE)?;
    let lossless = RasterImage::decode(LOSSLESS_TWELVE)?;
    assert_eq!(sequential, progressive);
    assert_eq!(
        sequential.pixels(),
        [0_u8, 128, 255]
            .into_iter()
            .flat_map(|sample| [Color::rgb(sample, sample, sample); 8])
            .collect::<Vec<_>>()
            .repeat(8)
    );
    assert_eq!((lossless.width(), lossless.height()), (5, 4));
    assert_eq!(lossless.pixels()[0], Color::BLACK);
    assert_eq!(lossless.pixels()[1], Color::WHITE);
    assert_eq!(lossless.pixels()[2], Color::rgb(128, 128, 128));
    assert_eq!(lossless.pixels().last(), Some(&Color::BLACK));

    render_sample(
        frame,
        "ARITH SEQ",
        sequential,
        Rect::new(422, 270, 84, 24),
        Rect::new(428, 270, 72, 24),
        [Color::BLACK, Color::WHITE],
    )?;
    render_sample(
        frame,
        "ARITH PROG",
        progressive,
        Rect::new(518, 270, 84, 24),
        Rect::new(524, 270, 72, 24),
        [Color::BLACK, Color::WHITE],
    )?;
    render_sample(
        frame,
        "ARITH 12B LOSSLESS",
        lossless,
        Rect::new(614, 270, 168, 24),
        Rect::new(683, 270, 30, 24),
        [Color::BLACK, Color::BLACK],
    )
}
