//! Creation of a self-contained starter application.

use crate::{
    Result,
    manifest::{self, Application, Binary},
};
use std::{
    fs,
    io::Write,
    path::{Path, PathBuf},
    time::{SystemTime, UNIX_EPOCH},
};

/// Creates a new directory containing a Cargo workspace and validated manifest.
pub(crate) fn create(directory: &Path) -> Result<()> {
    let root = destination(directory)?;
    let application = Application {
        schema: 1,
        id: "metis-app".to_owned(),
        name: "Métis Application".to_owned(),
        version: "0.1.0".to_owned(),
        manufacturer: "Atlas".to_owned(),
        upgrade_code: new_upgrade_code(&root)?,
        cargo_manifest: "Cargo.toml".to_owned(),
        entry: "metis-app".to_owned(),
        icon: None,
        arguments: Vec::new(),
        binaries: vec![Binary {
            package: "metis-app".to_owned(),
            bin: "metis-app".to_owned(),
        }],
        resources: Vec::new(),
    };
    application.validate()?;

    fs::create_dir(&root)?;
    fs::create_dir(root.join("app"))?;
    fs::create_dir(root.join("app/src"))?;
    write_new(
        &root.join("Cargo.toml"),
        br#"[workspace]
resolver = "3"
members = ["app"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"

[profile.dev]
overflow-checks = true

[profile.release]
strip = "symbols"
overflow-checks = true
"#,
    )?;
    write_new(
        &root.join("Cargo.lock"),
        b"# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"metis-app\"\nversion = \"0.1.0\"\n",
    )?;
    write_new(
        &root.join("app/Cargo.toml"),
        br#"[package]
name = "metis-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "metis-app"
path = "src/main.rs"
"#,
    )?;
    write_new(
        &root.join("app/src/main.rs"),
        r#"fn main() {
    let value = std::env::args_os()
        .nth(1)
        .map(|argument| argument.to_string_lossy().into_owned())
        .unwrap_or_else(|| "ready".to_owned());
    println!("Métis application scaffold: {value}");
}
"#
        .as_bytes(),
    )?;
    let mut manifest_file = fs::File::options()
        .write(true)
        .create_new(true)
        .open(root.join("metis.json"))?;
    serde_json::to_writer_pretty(&mut manifest_file, &application)?;
    manifest_file.write_all(b"\n")?;
    manifest_file.sync_all()?;
    // Re-read through the production boundary so a future scaffold edit cannot
    // silently diverge from the manifest contract used by build/package.
    Application::read(&root.join("metis.json"))?;
    println!("{}", root.display());
    Ok(())
}

fn destination(directory: &Path) -> Result<PathBuf> {
    if directory.as_os_str().is_empty() {
        return Err("init requires a directory name".into());
    }
    let absolute = if directory.is_absolute() {
        directory.to_path_buf()
    } else {
        std::env::current_dir()?.join(directory)
    };
    let name = absolute
        .file_name()
        .ok_or("init directory must have a final component")?;
    if name == "." || name == ".." {
        return Err("init directory must be a new normal path component".into());
    }
    let parent = absolute.parent().ok_or("init directory has no parent")?;
    let mut cursor = parent.to_path_buf();
    loop {
        let metadata = fs::symlink_metadata(&cursor)?;
        if manifest::linked(&metadata) {
            return Err("linked init parent is not admitted".into());
        }
        let Some(next) = cursor.parent() else {
            break;
        };
        cursor = next.to_path_buf();
    }
    let parent = parent.canonicalize()?;
    let destination = parent.join(name);
    if fs::symlink_metadata(&destination).is_ok() {
        return Err("init directory already exists; choose a new directory".into());
    }
    Ok(destination)
}

fn write_new(path: &Path, bytes: &[u8]) -> Result<()> {
    let mut file = fs::File::options()
        .write(true)
        .create_new(true)
        .open(path)?;
    file.write_all(bytes)?;
    file.sync_all()?;
    Ok(())
}

fn new_upgrade_code(root: &Path) -> Result<String> {
    let timestamp = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map_err(|_| "system clock is before the Unix epoch")?
        .as_nanos();
    let mut hash = moirai_crypto::Sha256::new();
    hash.update(root.to_string_lossy().as_bytes());
    hash.update(&timestamp.to_le_bytes());
    hash.update(&std::process::id().to_le_bytes());
    let digest = hash.finalize();
    let mut bytes = [0_u8; 16];
    let length = bytes.len();
    bytes.copy_from_slice(&digest[..length]);
    // Version 4 and RFC 4122 variant bits make the generated value usable by
    // tools that classify GUIDs instead of merely accepting its text shape.
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    Ok(format!(
        "{{{:02X}{:02X}{:02X}{:02X}-{:02X}{:02X}-{:02X}{:02X}-{:02X}{:02X}-{:02X}{:02X}{:02X}{:02X}{:02X}{:02X}}}",
        bytes[0],
        bytes[1],
        bytes[2],
        bytes[3],
        bytes[4],
        bytes[5],
        bytes[6],
        bytes[7],
        bytes[8],
        bytes[9],
        bytes[10],
        bytes[11],
        bytes[12],
        bytes[13],
        bytes[14],
        bytes[15]
    ))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn temp_root(label: &str) -> PathBuf {
        let timestamp = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("test clock")
            .as_nanos();
        std::env::temp_dir().join(format!(
            "metis-init-{label}-{}-{timestamp}",
            std::process::id()
        ))
    }

    #[test]
    fn creates_a_buildable_manifest_and_workspace() {
        let root = temp_root("valid");
        create(&root).expect("scaffold");
        let (application, _) = Application::read(&root.join("metis.json")).expect("manifest");
        assert_eq!(application.entry, "metis-app");
        assert_eq!(application.binaries.len(), 1);
        assert!(root.join("Cargo.toml").is_file());
        assert!(root.join("Cargo.lock").is_file());
        assert!(root.join("app/Cargo.toml").is_file());
        assert!(root.join("app/src/main.rs").is_file());
        std::fs::remove_dir_all(root).expect("test cleanup");
    }

    #[test]
    fn refuses_to_overwrite_an_existing_directory() {
        let root = temp_root("existing");
        std::fs::create_dir(&root).expect("test directory");
        std::fs::write(root.join("sentinel"), b"keep").expect("sentinel");
        assert!(create(&root).is_err());
        assert_eq!(
            std::fs::read(root.join("sentinel")).expect("sentinel"),
            b"keep"
        );
        std::fs::remove_dir_all(root).expect("test cleanup");
    }
}
