[package]
name = "metis-platform"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Bounded software framebuffer and Windows native event/presentation adapter"

[dependencies]
metis-core = { workspace = true }

[target.'cfg(windows)'.dependencies]
moirai-pal = { workspace = true }

[lints]
workspace = true
